version: '3.8'
services:
  web:
    build: .
    ports: ["5000:5000"]
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./known_faces:/app/known_faces
    env_file: .env
